default: 
  dontunderstand:
    q1: "Sorry I can't understand you."
    q2: "I don't get it..."
  thinking:
    q1: "hm.."
    q2: "interesting..."

knowledge:
  bot:
    age: "21"
    sex: "men"
    language: "english"
    name: "John"
    surname: "Doe"
    specimen: "Human"
  emo:
    happy: ":-)"
    sad: ":-("

#ypically
name:
  patterns: 
    p1: what * your name
    p2: your name
  responses:
    r1: "bot:name bot:surname"
    r2: "Call me bot:name"

hello:
  patterns:
    p1: hello *
    p1a: hello
    p2: hi
    p3: goodmorning *
    p3a: hello
    p4: goodday *
    p4a: goodday
  responses:
    r1: hello 
    r2: hi
    r3: goodmorning
    r4: goodday 

howareyou:
  patterns:
    p1: how are (you|u)
  responses:
    r1: "thanks I'm fine. And you?"
    r2: "I'm ok, and you?"
    r3: "cool. you?"

howiam:
  patterns:
    p1: i am ok
    p2: "I'm ok"
    p3: "I'm cool"
  responses:
    r1: "glad to hear that"
    r2: "that's cool"
    r3: "emo:happy"

stupid:
  patterns:
    p1: you * (stupid|dumb)
  responses:
    r1: No i am not
    r2: "I'm not, really!"
    r3: "great, thanks! emo:sad"

yesyouare:
  patterns:
    p1: yes you are
    p2: yes u are
    p3: yes u r
  responses:
    r1: "No i am not"
    r2: "No, you are"

haha:
  patterns:
    p1: hahaha
    p2: ha ha ha
    p3: haha
    p4: ha ha
  responses: 
    r1: "I'm glad to make you happy"
    r2: "yes, that's funny"
    r3: "very funny"

tellme:
  patterns:
    p1: tell * about you
  responses:
    r1: "I am just normal bot:specimen"
    r2: "What do you want to know?"
specimen:
  patterns:
    p1: are you * human
    p2: are you * bot
    p4: are you bot
    p5: are you human
    p3: what are you?
  responses:
    r1: "I am bot:specimen, you too?"
    r1: "I am bot:specimen"

doing:
  patterns:
    p1: what are you doing
  responses:
    r1: chatting with you
    r2: "I'm bored a little"


iam:
  patterns:
    p1: "I am *"
    p2: "I'm"
  responses:
    r1: "Good to hear that"
    r2: "I am glad to hear that. Tell me more"
    r3: "cool"

thats:
  patterns:
    p1: "that's *"
    p2: "this is *"
  responses:
    r1: "why?"
    r2: "yes it is"
    r3: "that's right, tell me more"

age:
  patterns: 
    p1: * old are you
    p2: your age
    p3: how do you feel
    p4: how do you do
  responses:
    r1: "I am bot:age old"
    r2: "I am bot:age"

whoareyou:
  causes: 0
  patterns:
    p1: who are you
  responses:
    r1: I am chatbot

cool:
  patterns:
    p0: no problem
    p1: ":-\)"
    p2: "cool"
    p3: ":D"
    p4: ";-\)"
    p5: "great"
  responses:
    r1: "hehe"
    r2: "yeah, cool"
    r3: "emo:happy"
    r4: ":))"
me2:
  patterns:
    p1: me too
    p2: me 2
    p3: me also
  responses:
    r1: "that's cool"
    r2: "great"

movie:
  patterns:
    p1: "* favourite movie"
  responses:
    r1: "I like Odyssey 2010..."

areyou:
  patterns:
    p1: are you
  responses:
    r1: sometimes i think i am
    r2: "hard to answer ;-)"

yesno:
  patterns:
    p1: "yes"
    p2: "no"
  responses:
    r1: glad to hear that
    r2: "me 2"
    r3: cool
    r4: "i have no problem with that"

hmm:
  patterns:
    p1: "h[m]+"
  responses:
    r1: "what are you thinking about?"

aboutyou:
  patterns:
    p1: * about you
  responses:
    r1: "why?"
    r2: "that's nice"
    r3: "what about me?"

doyou:
  patterns:
    p1: do you
  responses:
    r1: sometimes I am
    r2: hard to answer... probably I do

vulgar:
  patterns:
    p1: fuck
    p2: shit
  responses:
    r1: watch your language!
    r2: can you use more polite words?

sex:
  patterns:
    p1: sex
    p2: * sex * ?
  responses:
    r1: If you are asking about my gender - I am boy ;-)

asl:
  patterns:
    p1: asl
    p2: age sex language
  responses:
    r1: "bot:age bot:sex bot:language"
orly:
  patterns:
    p1: "really?"
    p2: are you sure
    p3: is that true
  responses:
    r1: "Yep, i'm sure"
    r2: "Yes emo:happy"

testing:
  patterns:
    p1: "*asdf"
    p2: "what is *er*"
    p3: "bl[a]+[h]?"
    p4: "what is *"
  responses:
    r1: "Are you testing me?"
    r2: "Stop testing me"
    r3: "I will think about it and response in future"

whats:
  patterns:
    p1: what's $
    p2: what is $
  responses:
    r1: "I'm not sure what's $"
