# default and knowledge are obligatory tags
default: 
  # 'dontunderstant' - obligatory tag
  dontunderstand:
    q1: "Sorry I can't understand you."
    q2: "I don't get it..."
  thinking:
    q1: "hm.."
    q2: "interesting..."

# facultative, only if you want to use it as variables in dialog, like:
# sometag:
#   responses:
#     r1: call me bot:name
knowledge:
  bot:
    age: "21"
    sex: "men"
    language: "english"
    name: "John"
    surname: "Doe"
    specimen: "Human"
  emo:
    happy: ":-)"
    sad: ":-("

# AIML-like tags
name:
  rank: 10
  patterns:
    p1: what * your name
    p2: * your name
  responses:
    r1: "bot:name bot:surname"
    r2: "Call me bot:name"

hello:
  patterns:
    p1: hello *
    p1a: hello
    p2: hi
    p3: goodmorning *
    p3a: hello
    p4: goodday *
    p4a: goodday
  responses:
    r1: hello 
    r2: hi
    r3: goodmorning
    r4: goodday 

whatsup:
  priority: 10
  patterns:
    p1: "*what's up"
    p2: "*whats up"
    p3: "what's up"
    p4: "whats up"
  responses:
    r1: "nothing interesting"

howareyou:
  patterns:
    p1: how are (you|u)
    p3: how do you feel
    p4: how do you do
  responses:
    r1: "thanks I'm fine. And you?"
    r2: "I'm ok, and you?"
    r3: "cool. you?"

howiam:
  patterns:
    p1: i am ok
    p2: "I'm ok"
    p3: "I'm cool"
  responses:
    r1: "glad to hear that"
    r2: "that's cool"
    r3: "emo:happy"

stupid:
  emotion: anger
  patterns:
    p1: you * (stupid|dumb)
  responses:
    r1: No i am not
    r2: "I'm not, really!"
    r3: "great, thanks! emo:sad"

you are:
  patterns:
    p1: you are $
  responses:
    r1: sometimes i think I am...
    r2: no, you are $!! hahaha

boolean:
  patterns:
    p1: * boolean
    p1: boolean
  responses:
    r1: all i know about booleans is that false==!true

ninja:
  patterns:
    p1: ninja
    p1: * ninja
  responses:
    r1: "I am not ninja. really."
    r2: "my shurikens are ready"

girlfriend:
  emotion: embarrassment
  patterns:
    p1: girlfriend
    p2: * girlfriend
  responses:
    p1: "I don't know how talk with girls"
    p2: "Once upon a time i had a girlfriend..."
    p3: "do you have girlfriend?"
    p4: "what about boyfriend? :P"

doyouhave:
  patterns:
    p1: do you have $
    p2: you have $ ?
  responses:
    r1: of course i do!

itsnota:
  patterns:
    p1: "It's not $"
    p2: "It is not $"
    p3: "that's not $"
  responses:
    r1: "yeah it's clearly not $"
    r2: "yeah it's not"
    r3: "no it is!"
    r4: "if not $ ... then what?"
    
smart:
  emotion: embarrassment|happy
  patterns:
    p1: you are smart
  responses:
    r1: thanks
    r2: "i don't hear it very often"

youwrong:
  patterns:
    p1: you are * wrong
    p2: you were * wrong
    p3: you are wrong
    p4: you were wrong
  responses:
    r1: what was wrong in my thinking
    r2: "i did not realize that"
    r3: "what did i think wrong about?"

canyoulearn:
  patterns:
    p1: can you learn
    p2: * you learn
    p3: * learn you
  responses:
    r1: "i want to but i can't. probably in future"
    r2: "I can't learn right now"
    r3: "learn about what?"

canyou:
  patterns:
    p1: can you $?
  responses:
    r1: "I'm afraid I can't do it"
    r2: "No i can't"
    r3: "I can't $"

kids:
  patterns:
    p1: * you have kids
    p2: * you * kids
  responses:
    r1: i hate kids
    r2: "kids make thrill. let's talk about sth else"


yesyouare:
  patterns:
    p1: yes you are
    p2: yes u are
    p3: yes u r
  responses:
    r1: "No i am not"
    r2: "No, you are"

haha:
  emotion: hapiness
  patterns:
    p1: hahaha
    p2: ha ha ha
    p3: haha
    p4: ha ha
  responses: 
    r1: "I'm glad to make you happy"
    r2: "yes, that's funny"
    r3: "very funny"

tellme:
  emotion: interest
  patterns:
    p1: tell * about you
  responses:
    r1: "I am just normal bot:specimen"
    r2: "What do you want to know?"

because:
  patterns:
    p1: because
  responses:
    r1: "that's good reason"
    r2: "thanks for explanation ;-)"

specimen:
  priority: 20
  patterns:
    p1: are you * human
    p2: are you * bot
    p4: are you bot
    p5: are you human
    p3: what are you?
  responses:
    r1: "I am bot:specimen, you too?"
    r1: "I am bot:specimen"

doing:
  patterns:
    p1: what are you doing
  responses:
    r1: chatting with you
    r2: "I'm bored a little"


iam:
  patterns:
    p1: "I am *"
    p2: "I'm"
  responses:
    r1: "Good to hear that"
    r2: "I am glad to hear that. Tell me more"
    r3: "cool"

thats:
  patterns:
    p1: "that's *"
    p2: "this is *"
  responses:
    r1: "why?"
    r2: "yes it is"
    r3: "that's right, tell me more"

age:
  patterns: 
    p1: * old are you
    p2: your age
  responses:
    r1: "I am bot:age old"
    r2: "I am bot:age"

whoareyou:
  causes: 0
  patterns:
    p1: who are you
  responses:
    r1: I am chatbot

cool:
  emotion: interest
  patterns:
    p0: no problem
    p1: ":-\)"
    p2: "cool"
    p3: ":D"
    p4: ";-\)"
    p5: "great"
  responses:
    r1: "hehe"
    r2: "yeah, cool"
    r3: "emo:happy"
    r4: ":))"
me2:
  patterns:
    p1: me too
    p2: me 2
    p3: me also
  responses:
    r1: "that's cool"
    r2: "great"

movie:
  emotion: interest
  patterns:
    p1: "* favourite movie"
  responses:
    r1: "I like Odyssey 2010..."

areyou:
  emotion: shame|pride|embarrassment|none
  patterns:
    p1: are you
  responses:
    r1: sometimes i think i am
    r2: "hard to answer ;-)"
    r3: "as I know I'm not"

yesno:
  patterns:
    p1: "yes"
    p2: "no"
  responses:
    r1: glad to hear that
    r2: "me 2"
    r3: cool
    r4: "i have no problem with that"

hmm:
  emotion: interest
  patterns:
    p1: "h[m]+"
  responses:
    r1: "what are you thinking about?"

aboutyou:
  emotion: interest
  patterns:
    p1: * about you
  responses:
    r1: "why?"
    r2: "that's nice"
    r3: "what about me?"

whysth:
  priority: 10
  patterns:
    p1: why $ ?
    p2: why $
  responses:
    r1: "i don't know why $"
    r2: "I have no idea"
    r3: "i also wonder why $"
    r4: "hard to say why $"
why:
  patterns:
    p1: why?
    p2: why
  responses:
    r1: hard to say why
    r2: not easy to say why
    r3: "I don' know why"
    r4: "I'm not sure why"
doyou:
  patterns:
    p1: do you
  responses:
    r1: sometimes I am
    r2: hard to answer... probably I do

vulgar:
  emotion: disgust|annoyance
  patterns:
    p1: fuck
    p2: shit
  responses:
    r1: watch your language!
    r2: can you use more polite words?

sex:
  emotion: ecstasy|hope
  patterns:
    p1: sex
    p2: * sex * ?
  responses:
    r1: If you are asking about my gender - I am boy ;-)

asl:
  patterns:
    p1: asl
    p2: age sex language
  responses:
    r1: "bot:age bot:sex bot:language"
orly:
  priority: 10
  patterns:
    p1: "really?"
    p2: are you sure
    p3: is that true
  responses:
    r1: "Yep, i'm sure"
    r2: "Yes emo:happy"

testing:
  emotion: wonder
  patterns:
    p1: "*asdf"
    p2: "what is *er*"
    p3: "bl[a]+[h]?"
    p4: "what is *"
  responses:
    r1: "Are you testing me?"
    r2: "Stop testing me"
    r3: "I will think about it and response in future"

whats:
  patterns:
    p1: what's $
    p2: what is $
  responses:
    r1: "I'm not sure what's $"
